# Generated by Django 6.0.1 on 2026-01-18 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('code_cmd', models.AutoField(primary_key=True, serialize=False)),
                ('quantite_cmd', models.IntegerField(default=1)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('code_prod', models.AutoField(primary_key=True, serialize=False)),
                ('nom_prod', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantite', models.IntegerField(default=0)),
                ('prix_unit', models.FloatField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Produits',
                'ordering': ['nom_prod'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('code_facture', models.AutoField(primary_key=True, serialize=False)),
                ('montant_total', models.FloatField()),
                ('date_facture', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('validee', 'Validée'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='brouillon', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='facture', to='stock.commande')),
            ],
            options={
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_facture'],
            },
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_objet', models.CharField(choices=[('produit', 'Produit'), ('commande', 'Commande'), ('facture', 'Facture')], max_length=20)),
                ('id_objet', models.IntegerField()),
                ('donnees_supprimees', models.JSONField()),
                ('date_suppression', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Historiques',
                'ordering': ['-date_suppression'],
                'indexes': [models.Index(fields=['type_objet', 'date_suppression'], name='stock_histo_type_ob_fafb0b_idx')],
            },
        ),
        migrations.AddField(
            model_name='commande',
            name='code_prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='stock.produit'),
        ),
    ]
