# Generated by Django 6.0.1 on 2026-01-18 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('code_fournisseur', models.AutoField(primary_key=True, serialize=False)),
                ('nom_fournisseur', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('is_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom_fournisseur'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('code_notification', models.AutoField(primary_key=True, serialize=False)),
                ('type_notification', models.CharField(choices=[('rupture', 'Rupture de Stock'), ('alerte_basse', 'Stock Bas'), ('commande_confirmee', 'Commande Confirmée'), ('facture_payee', 'Facture Payée'), ('fournisseur_contact', 'Fournisseur Contacté')], max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('est_lue', models.BooleanField(default=False)),
                ('est_traitee', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='stock.fournisseur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='stock.produit')),
            ],
            options={
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['est_lue', 'est_traitee'], name='stock_notif_est_lue_472dd4_idx'), models.Index(fields=['-date_creation'], name='stock_notif_date_cr_d367b6_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProduitFournisseur',
            fields=[
                ('code_liaison', models.AutoField(primary_key=True, serialize=False)),
                ('prix_fournisseur', models.FloatField()),
                ('delai_livraison', models.IntegerField(default=7)),
                ('quantite_min', models.IntegerField(default=10)),
                ('is_principal', models.BooleanField(default=False)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='stock.fournisseur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fournisseurs', to='stock.produit')),
            ],
            options={
                'verbose_name_plural': 'Produits-Fournisseurs',
                'ordering': ['-is_principal', 'prix_fournisseur'],
                'unique_together': {('produit', 'fournisseur')},
            },
        ),
    ]
