# Generated by Django 6.0.1 on 2026-01-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_fournisseur_notification_produitfournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='photo',
            field=models.ImageField(blank=True, help_text='Téléchargez une image du produit (PNG, JPG, JPEG)', null=True, upload_to='produits/%Y/%m/%d/', verbose_name='Photo du produit'),
        ),
    ]
