# Generated by Django 6.0.1 on 2026-01-19 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_produit_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='agent_utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facture',
            name='agent_utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='produit',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits_fournis', to='stock.fournisseur'),
        ),
        migrations.CreateModel(
            name='MontantAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total', models.FloatField(default=0.0)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('agent_utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='montant_commandes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Montants Agents',
            },
        ),
    ]
