# Generated by Django 6.0.1 on 2026-01-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_commande_agent_utilisateur_facture_agent_utilisateur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fournisseur',
            name='is_actif',
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='actif', max_length=20),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='code_fournisseur',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
