# Generated by Django 6.0.1 on 2026-01-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_remove_fournisseur_is_actif_fournisseur_statut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='mot_de_passe',
            field=models.CharField(blank=True, help_text="Mot de passe pour l'accès au dashboard", max_length=100, null=True),
        ),
    ]
