# Generated by Django 6.0.1 on 2026-01-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_fournisseur_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='nom_prod',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='produit',
            unique_together={('fournisseur', 'nom_prod')},
        ),
    ]
