# Generated by Django 6.0.1 on 2026-01-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_alter_produit_nom_prod_alter_produit_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='statut_paiement',
            field=models.CharField(choices=[('en_attente', 'En Attente de Paiement'), ('payee', 'Payée')], default='en_attente', max_length=20),
        ),
    ]
