# Generated by Django 6.0.1 on 2026-01-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_commande_statut_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_paiement',
            field=models.DateTimeField(blank=True, help_text='Date du paiement confirmé', null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='paiement_confirme',
            field=models.BooleanField(default=False, help_text='Confirmé par le fournisseur'),
        ),
    ]
