# Generated by Django 6.0.1 on 2026-01-21 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_commande_date_paiement_commande_paiement_confirme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='commande',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facture', to='stock.commande'),
        ),
    ]
